name: Test Config Pass

on:
  pull_request:
    paths-ignore:
      - 'src/config/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: [14]
    name: Config (Jest)
    steps:
      - run: 'echo "No Test Config required" '
